### ISSUE TITLE
Actual 0.13 Checklist 

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#1091]
- [x] New advancements
- [x] Modonomicon Icons fixed and new entries for extended / gems 
- [x] #1082 
- [x] Full better combat integration
- [x] Tools need stats 
- [x] Tools need handlers 
- [x] Tools need their own types (spear, club etc) 
- [x] Remove all offsets
- [x] Tools need to be added to villagers
- [x] Rename club type to swordlike / weapon

Need siggs helps 
- [x] Predicate for throwing to add offsets 
- [x] Better combat reach integration
- [x] Is there a possibility tools can appear larger without changing the texture? spears/greatswords look really small in third person
- [x] Handle recipe errors

just found bug? 

- [x] dye template on mastercrafted pommel
- [x] Okay check all dyes something fishy going on
- [x] Recipes for new types dont work without RESOURCE_TYPE: DEFAULT enabled
