### ISSUE TITLE
Work on dynamically re-colouring textures, either on runtime, or on startup

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#2]
To decrease the number of custom textures i need to create, I should find a way to recolour textures on the fly. In this configuration I only need to create the base textures, and keep all the different colours needed to represent an increasing number of materials.

### Textures
- Handle
- Half handle
- Short handle
- Pickaxe binding
- Shovel Binding
- Base binding
- Shovel head
- Pickaxe head

### Materials
Oak
Birch 
Spruce
Stone
Iron
Gold
Diamond
Netherite

### Tasks

- [x] Create a basic system for generating textures for all models with the listed materials
- [x] Refine colour palettes 
- [x] Create possibility for using already defined palettes
- [x] #12
- [x] Reconsider naming conventions
- [x] Reconsider API structure, and clean up the code
- [x] Add the possibility to return Resource from created pictures
- [x] Document the Texture creation API
- [x] Move recolorization to each item part texture
- [x] Add possibility to choose from different "Strategies" when colourizing tool parts
