### ISSUE TITLE
WIP Compat mod support

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#211]
This is our issue/thread for seeing which mods are supported, which are being worked on and to ask mod support for new mods! 

### Not started yet (asking for help; ordered by importance)

- [ ] Botania
- [ ] Spelunkery
- [ ] Galosphere
- [ ] Edenring
- [ ] Twilight Forest
- [ ] ComputerCraft
- [ ] Gobber
- [ ] Amethyst Imbuement
- [ ] Dungeon Now Loading
- [ ] Majrusz' Progressive Difficulty
- [ ] Mine Cells

### Redo required (old compat; new features, updated textures, etc.)
- [ ]  Mythic Metals 
- [x]  Better Nether
- [x] Ad Astra

### Done
- [ ] Mythic Metals Decorations (#1016)
- [ ] Lets do series (#1013 #1014 #1007 #1012 #1003) 
- [ ] Gardens of the dead (#1015 )
- [ ] Tech Reborn (#996)
- [ ] Modern Industrialization (#995)
- [x] Regions Unexplored (#944)
- [x] Better End (#957)
- [x] Create (#974)
- [x] Ecologics (#958)
- [x] Naturalist (#937)
- [x] Deeper and Darker (#949)
- [x] Ad Astra (#975)
- [x] Advanced Netherite (#981)

#### May need a revisit

- [ ] Wired Redstone (#178)
- [ ] Smithee's Foundry (#190)
- [x] Mythic Metals (#213)
- [x] LambDynamicLights (#217)
- [ ] Alloygery (#219)
- [x] EMI Loot (#337)
- [x] Better Combat (#390)
- [ ] Applied Energistics 2 (#443)
- [ ] Sword Parry (#470)
- [ ] Variant Sticks & Stuff (#497)
- [x] Better Nether (#596; #960)
- [ ] Farmer's Delight (#731; #771)
- [ ] Origins #647 
- [ ] Graveyards (#384)
- [ ] Nox (#677)

**Comment by Andrew6rant** [comment]
[EMI](https://modrinth.com/mod/emi) Integration would be really nice. Right now only the mod's recipes with schematics are displayed

**Comment by SigmundGranaas** [comment]
Alright, I have no experience with this mod, but I'll see if I can work on integrating the recipes better 👍

**Comment by Steveplays28** [comment]
Just linking #326 (Mod Menu Integration) here for anyone reading. Got implemented and should be ready for 0.11 if I'm keeping track correctly

**Comment by SigmundGranaas** [comment]
That's correct

**Comment by DanMeadWasTaken** [comment]
What about some [Expert weapons & tools](https://www.curseforge.com/minecraft/mc-mods/expert-weapons) integration? Basically if it's present, then use their recipes or parts?

**Comment by SigmundGranaas** [comment]
I am not familiar with this mod, but it looks to me like it's making changes to vanilla progression by changing how tools are crafted. Forgero also does this, but does this by providing a complete part, upgrade and property system.

It's possible to create an extension mod that attaches forgero properties to the items provided and add recipes for this, but this would probably require more work by the author of expert weapons and tools to be useful.

I might be missing something, but I don't think using the mods recipes is something that would make sense for Forgero

**Comment by DanMeadWasTaken** [comment]
How hard would it be for someone to then instead make a extension mod to basically replicate the expert tools recipes into forgero or for the modpack creator to be able to just change the forgero recipes to do something similar

**Comment by Steveplays28** [comment]
@DanMeadWasTaken You could use the [Forgero example extension pack](https://github.com/SigmundGranaas/forgero-example-datapack) as a framework to add compatibility. You could copy their textures and override Forgero textures with them using a datapack.

**Comment by DanMeadWasTaken** [comment]
Alright, thankyou! I'll look into this, trying to make my own modpack, but wanted progression to be a bit harder- and thus wanted the sorta recipes expert weapons & tools uses. Although i was thinking i may just need to change recipes using something like kubejs

**Comment by Steveplays28** [comment]
Datapacks (and Forgero extension packs) can change recipes too! Less fragile than KubeJS in my experience, though use what you like.
Good luck with the modpack!

**Comment by DanMeadWasTaken** [comment]
I almost forgot! My other suggestion was one that is pretty prominent these days:  [Advanced Netherite](https://www.curseforge.com/minecraft/mc-mods/advanced-netherite-fabric)

**Comment by Steveplays28** [comment]
I've seen that mod before! Definitely doable, feel free to open a separate issue and we'll track it here.

**Comment by Steveplays28** [comment]
Thanks for opening the issues @DanMeadWasTaken!

**Comment by DanMeadWasTaken** [comment]
No problem lol
I've basically already had to go around for about a month now just reporting bugs and making suggestions, it's always nice to have a mod creator/collaborator that responds/gives feedback.

**Comment by SigmundGranaas** [comment]
Damn, Steve is keeping it up with awesome responses, thanks for your suggestions Daniel!

**Comment by SigmundGranaas** [comment]
Just wanna give a small update on this issue now. I had some time to play around with some of the stuff that is required for this compatibility to work.

I created a branch to work on some of the basic parts to get that working first.

### Texture scaling and display overrides
I managed to get dynamic resolution scaling to work, which means that normal 16x16 textures can be scaled down to fit 32x32 textures dynamically, so everything that is needed is to apply manual texture offsets to parts that need to be shifted to be in the correct place.

Display overrides also works, so the custom display model attributes of simply swords tools can also be used.

Here's some pictures of this working:

![image2](https://github.com/SigmundGranaas/forgero/assets/46557903/ff3b353f-d9a4-4cdd-8b7b-5a32a00870b5)

![image1](https://github.com/SigmundGranaas/forgero/assets/46557903/4d110834-2a76-486d-99d9-560ad099a8a6)

### Animated texture layers
I am currently working on implementing a system for adding custom texture layer elements, which will make it possible to recreate lots of the elemental effects on some of the swords. This will be tracked in this branch: #623 

[Screencast from 2023-05-29 22-32-36.webm](https://github.com/SigmundGranaas/forgero/assets/46557903/21f90f8d-0f60-4eb4-80e0-825a7db6f083)

Stuff that still needs work:
- [ ] #622 
- [ ] Integrated support for the custom feature/properties of the weapons
- [ ] Support for combining the tooltips of both mods
- [ ] Actually implement all of the different weapons

When The code required to complete this compat is done, I will likely ask from support in the community to actually create and fine tune all of the schematics, textures, parts and models. Creating compatability for the basic tool variants should be fully supported now.

**Comment by ChromaPIE** [comment]
If it's the correct place to leave a mod support request I would more than love to have a [GregTechCEu Modern](https://modrinth.com/mod/gregtechceu-modern) support! Much appreciation!

**Comment by SigmundGranaas** [comment]
> If it's the correct place to leave a mod support request I would more than love to have a [GregTechCEu Modern](https://modrinth.com/mod/gregtechceu-modern) support! Much appreciation!

We appreciate the request for new compats to Forgero! GregTech's list of materials is a little too big, so it probably won't receive a compat module from the core team, although if some brave soul wants to create the compat, we are open for providing the support needed to get it going!

**Comment by Lyuu17** [comment]
hello, [Ice and Fire CE](https://modrinth.com/mod/iceandfire-ce) integration would be awesome
