### ISSUE TITLE
Stone golem

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#260]

**Comment by SigmundGranaas** [comment]
### TODO

- [ ] Create textures and finalize models
- [x] Create the navigate to ore goal
- [ ] Create the create tunnel goal when no ore is being found
- [x] Create the eat ore goal
- [ ] Implement pickaxe damage boost
- [ ] animate the beast
- [ ] Add right click belly button to drop inventory

**Comment by JorisDeBeer** [comment]
Out of scope / outdated / maybe added later date?
