### ISSUE TITLE
Look into a system for unifying different attribute bonuses / abilities.

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#44]
Every tool part, material and gem has attributes hard-coded, and each attribute needs to be handled specifically. This leads to a lot of verbose code and a very rigid system. I need to look into system, like EntityAttributes which can be recongnised at different parts in the game.

TLDR; the current system is very rigid, making changing things up really hard.

**Comment by SigmundGranaas** [comment]
### Idea
Handle all properties of tool parts with the same type of attributes. This means treating all properties of all tool parts as a "pool" of properties, which will be gathered, sorted and computed whenever the tool is used.

I see no reason for restricting which properties can be applied to any tool part/gem in code. There are of curse a lot of properties which don't belong on certain materials or gems, but that decision should be handled when creating the resources. 

I need to create some core types of attributes which can be filtered when calculating properties. If I can efficiently stream attributes i can create a sort of DSL to gather the right properties.

Categories
- Mining speed
- Mining level
- Durability
- Attack speed
- Attack damage
- Passive attributes
- Use attributes

#### Examples

```
{
  "properties": {
    "attributes": [
      {
        "attack_damage": {
          "order": "END",
          "type": "MULT",
          "value": 1.2,
          "condition": {
            "target": "ENTITY",
            "tag": "LIVING"
          }
        }
      },
      {
        "attack_speed": {
          "order": "BASE",
          "type": "ADD",
          "value": 3.0
        }
      },
      {
        "attack_speed": {
          "order": "BASE",
          "type": "ADD",
          "value": 3.0,
          "condition": {
            "target": "ENVIRONMENT",
            "tag": "DAY"
          }
        }
      },

      {
        "attack_damage": {
          "order": "BASE",
          "type": "ADD",
          "value": 3.0
        }
      }
    ],
    "passive": [
      {
        "type": "EMISSIVE",
        "value": 3.0
      },
      { "type": "GOLDEN" }
    ],
    "active": []
  }
}

```

**Comment by SigmundGranaas** [comment]
I have made a lot of progress regarding a new Attribute system. A basic version is implemented in #72. The main issue with the system is balancing the properties and figuring out which materials should boost which stats. This still needs some work. The system currently only supports attributes, as I have to figure out how to implement specific buffs later.

### TODO:
Here are some fields I need to work on before merging the new property system.

**Attributes:**
- [x] Create rules/calculations for how MINING_LEVEL attributes should be handled by tools
- [x] Scrub conditions when properties regarding tool parts and their placements are gathered from tool part state. This is important to allow tool parts specific buffs to be applied when you no longer know where they came from.
- [x] Add properties to gems and let them be recognised when fetching attributes.
- [x] Rework the target interface. The interface needs to be much better encapsulated, it is quite stupid right now.
- [x] Add rarity to properties.
- [x] Remove traces of the old attributes
- [x] Add edge case handling in case 
- [x] Figure out how Attack speed works and how to work with it. why is it negative
- [x] Decide on a way to handle negative attributes. Make sure properties does not end up negative and that negative scaling does not multiply with another negative, which ends up being positive.
- [x] Allow gem levels to affects properties

**General:**
- [x] List all properties associated with tools, gems and tool parts when viewing their descriptions.
- [x] Add baseline damage and attack speed to weapon heads, to make constructing Tool Items easier to initialize. Currently they need an extra float when being constructed because I was lazy when coding it.

**Documentation:**
- [x] Document the Attribute API and how it is used, all interfaces should be properly documented.
- [x] Document an example on the WIKI for how Materials and gems are described with JSON and what the properties mean.

**Tests:**
- [x] Create a baseline for how weapons should behave compared to vanilla behaviour
- [x] Create tests for making sure that some combination of tools won't be to powerful
- [x] Create tests for what happens when you approach edge cases
- [x] Verify conditions for properties with TOOL_PART_PLACEMENTS conditions.
- [x] Create a baseline test for what a diamond tool head should be able to achieve with a variety of upgrades. Secondary upgrades, gems, handles and bindings.
- [x] Create a baseline test for what a netherite tool should be able to achieve with a variety of upgrades. Secondary upgrades, gems, handles and bindings.
- [x] Create a baseline test for what a wooden tool should be able to achieve with a variety of upgrades. Secondary upgrades, gems, handles and bindings.
- [x] Create a baseline test for what a iron tool should be able to achieve with a variety of upgrades. Secondary upgrades, gems, handles and bindings.
