### ISSUE TITLE
[Update]: Forgero 0.11.6

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#773]
Things that should be done before 0.11.6 can be released.

- [x] #772 
- [x] #776 
- [x] Verify that health still work
- [x] Test Forgero with Bettercombat to make sure that the reach attribute still works
- [x] Verify that luck works as intended #777 
- [x] Verify that models works for sticks, and all other extension packs
- [x] Fix proper caching for features
- [x] #770 
- [x] Add new descriptions all states that use the new features #777 
- [x] Verify that tools with dynamic attributes have proper descriptions #777 
- [x] Fix missing recipes in patchouli book #778

**Comment by SigmundGranaas** [comment]
Fix these:
`[13:28:09] [Render thread/WARN]: Recipe forgero:pummel-schematic_recipe (of type minecraft:crafting) not found
[13:28:09] [Render thread/WARN]: Recipe forgero:copper-pummel (of type minecraft:crafting) not found
[13:28:09] [Render thread/WARN]: Recipe forgero:spiked_binding-schematic_recipe (of type minecraft:crafting) not found
[13:28:09] [Render thread/WARN]: Recipe forgero:gold-mastercrafted_handle-pummel (of type minecraft:smithing) not found
[13:28:09] [Render thread/WARN]: Recipe forgero:stone-mastercrafted_handle-material (of type minecraft:smithing) not found`
