### ISSUE TITLE
Bow release checklist 

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#796]
Stuff that needs doing before releasing the bow feature.

- [x] Ensure all bows and upgrades have unique models
- [x] Move all bow code and data into its own module
- [x] Create custom/better upgrades for arrows and bows
- [x] Decide on which attributes should be used to define flight properties for arrows/bows
- [x] Create a better way to craft/upgrade arrows
- [x] Add support for vanilla/modded arrows and bows work
- [x] Create a bow feature instead of hardcoding it

**Comment by JorisDeBeer** [comment]
**Bugs**
- [x] Handles with grip/reinforcement are allowed in arrows what causes clipping textures and a buggy look. 
- [x] Already built bows/arrows in the upgrade station bugs out hard need to decide if we allow this or not. 
- [x] For some reason the refined schematic png file errors randomly when starting up the game. Is pretty consistent but dont know why that is happening? 

**Should fix**
- [x] Tooltip with bows/arrows has too much stuff thats not being used / not the right things being displayed
- [x] Base arrow has stone head instead of a flint one
- [x] Add weight affecting draw speed

**Balancing**
- [x] Durability needs a fix ->(still need override) Special predicate override #843 
- [x] Attack damage on arrows should be looked at
- [x] Base bow stats
- [ ] Upgrades need to be done

**Comment by SigmundGranaas** [comment]
Some more notes:
- [x] Durability should decrease when shooting
- [x] Remove recipes for arrows based on anything but sticks

**Comment by SigmundGranaas** [comment]
More notes:
- [x] Add a limit to how low draw_speed can be, just like attack speed
- [x] Reverse the effect of weight on draw_speed. It's decreasing right now
- [x] Reverse draw speed calculation so it determines DPS (Draws per second)

**Comment by SigmundGranaas** [comment]
More notes:
- [x] Add tiered results to the arrow heads for mastercrafted/refined and vanilla

**Comment by JorisDeBeer** [comment]
- [x] Tooltip colors with a bow should just be white instead of draw speed being red already

**Comment by JorisDeBeer** [comment]
- [x] Handle texture seems weird let me check back tomorrow
