### ISSUE TITLE
[Release]: 0.12 Checklist

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#908]
There are a couple of things I want to get sorted before releasing 0.12. Mainly documentation and some assets.

## Todo:
- [x] Write a section in the docs about bows. How they work, which values are present and which attributes are used.
- [x] Bow rendering in 3rd person is looking mighty stupid

## Finished: 
- [x] Update the descriptions on CurseForge, Modrinth and Github to reflect the current state of the mod (I think?)
- [x] Updated extended to be up to date and use alot of the new features of the mod
- [x] First iteration of new gems
- [x] Update the banner assets to include a bow as well.

## 1.20.4
It is well underway and will be a part of the official release. It just needs to finish some testing and fix whatever is wrong with the bows. #916 
If there's nothing stopping me from porting to 1.20.5 and 1.20.6 I will do that as well.
