### ISSUE TITLE
Things needing to get fixed before extended release 1.0

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#910]
- [x] I BEG YOU I NEED A SWORD TYPE WITHOUT A GUARD PLEASE #912
- [x] Reach needs to be shown in the tooltip (Could make it so its only shown when being modified/when its not 4,5)
- [x] Higher reach then 4,5 onlyt the selector seems to work. Entities further out dont get hit and blocks just flikker and reappear #913
- [x] Throwing needs to be fixed (mostly the spinning and weight affecting the tool)  #914
- [x] Using a sneaking predicate completely breaks the tooltip on the tool (I used one there was and it just nukes the tooltip for some reason?)
- [x] Predicates using sneaking & sprinting dont seem to work
